# Generated by Django 6.0.6 on 2026-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_withdrawn', models.BooleanField(default=False)),
            ],
        ),
    ]
