# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [

        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, blank=True, null=True)),
            ],
        ),

        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(max_length=50)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='authentication.user'
                )),
            ],
        ),

        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='following',
                    to='authentication.user'
                )),
                ('related_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='followers',
                    to='authentication.user'
                )),
            ],
        ),

        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('Profile_photo', models.ImageField(upload_to='profiles/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]