# Generated by Django 6.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('Profile_photo', models.ImageField(upload_to='profiles/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
